# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Python Corner
email: mastro35@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A website about Python... only for real Pythonistas
twitter_username: mastro35
github_username: mastro35
minimal_mistakes_skin: dark
search: true
logo: /assets/images/logo.png

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /posts/:year-:month-:day-:slug/
# breadcrumbs: true
paginate: 7 # amount of posts to show
paginate_path: /page:num/
Timezone: PDT # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Include:
  - _pages
  - .well-known # for mastodon alias

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name   : "The Python Corner"
  avatar : "/assets/images/tpc.png"
  bio    : "made with ❤️ in Italy<br>only for real Pythonistas!"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.thepythoncorner.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/thepythoncorner"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/mastro35"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/mastro35"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/thepythoncorner"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "the-python-corner"

# analytics:
#  provider: "google-gtag"
#  google:
#    tracking_id: "UA-120027408-1"
#    anonymize_ip: false # default


