baseURL = "https://mastro35.github.io/tpc/"

relativeURLs = true
canonifyURLs = true

languageCode = "en-us"
title = "The Python Corner"
theme = "cactus"
copyright = "Davide Mastromatteo" # cactus will use title if copyright is not set
disqusShortname = "the-python-corner" # Used when comments is enabled. Cactus will use site title if not set
googleAnalytics = "UA-120027408-1"

#
# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Articles"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Help Us"
url = "/help_us"
weight = 5

[[menu.main]]
name = "Newsletter"
weight = 0
url = "https://buttondown.email/thepythoncorner"

[[menu.main]]
name = "Swag Store"
weight = 0
url = "https://shop.spreadshirt.com/the-python-corner"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[params]
  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  logo = "images/logo.png"
  description = ""
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 15 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/mastro35" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = true # default
    engine = "utterances" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "mastro35/tpc"
      label = "The Python Corner" # you can use however you want to label your name in your repo's issues
      theme = "github-dark"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/mastro35"
#  [[params.social]]
#    name = "linkedin"
#    link = "https://www.linkedin.com/company/github/"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/mastro35"
  [[params.social]]
    name = "email"
    link = "info@thepythoncorner.com"  # no need for "mailto:" in the head

[author]
  [author.davide_mastromatteo]
    name = "Davide Mastromatteo"
    location = "Milan - Italy"
  [author.andrew_zapisotskyi]
    name = "Andrew Zapisotskyi"
    location = "Ukraine"
